name: Build and release Brodsky

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64]
    outputs:
      release_name: ${{ steps.get_names.release_name }}
      tag_name: ${{ steps.get_names.tag_name }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Get names for release
      - name: Get names for release and tag
        id: get_names
        run: |
          RELEASE_NAME_TS=$(date '+%Y-%m-%d %H:%M:%S')
          TAG_NAME_TS=$(date '+%Y%m%d%H%M%S')

          echo "release_name=Pre-release $RELEASE_NAME_TS" >> $GITHUB_OUTPUT
          echo "tag_name=pre-release-$TAG_NAME_TS" >> $GITHUB_OUTPUT

      # Step 3: Set up Go environment
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      # Step 4: Build application
      - name: Build binaries
        run: |
          cd src
          mkdir -p ../build
          if [ "${{ matrix.os }}" = "windows" ]; then
            go build -ldflags "-X info.version=${{needs.build.outputs.tag_name}}" -o ../build/brodsky-${{ matrix.os }}-${{ matrix.arch }}.exe
          else
            go build -ldflags "-X info.version=${{needs.build.outputs.tag_name}}" -o ../build/brodsky-${{ matrix.os }}-${{ matrix.arch }}
          fi
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      
      # Step 5: Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: brodsky-${{ matrix.os }}-${{ matrix.arch }}
          path: build/brodsky-${{ matrix.os }}-${{ matrix.arch }}*
          if-no-files-found: error
          overwrite: true
          compression-level: 0

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build

    steps:

      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Download built files
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: build/
          merge-multiple: true

      # Step 3: Create ZIP archives
      - name: Package executables into ZIP archives
        run: |
          mkdir -p releases
          cd build
          mv brodsky-linux-amd64 brodsky
          zip -j ../releases/brodsky-linux-amd64.zip brodsky
          rm brodsky
          mv brodsky-darwin-amd64 brodsky
          zip -j ../releases/brodsky-darwin-amd64.zip brodsky
          rm brodsky
          mv brodsky-windows-amd64.exe brodsky.exe
          zip -j ../releases/brodsky-windows-amd64.zip brodsky.exe
          rm brodsky.exe
          cd ..

      # Step 4: Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_names.outputs.tag_name }}
          name: ${{ steps.get_names.outputs.release_name }}
          prerelease: true
          make_latest: 'true'
          files: releases/*
          token: ${{github.token}}
